In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import model_selection

In [ ]:
dir_name = "/content/drive/MyDrive/set/" #Переменная, хранящая путь к файлам пациентов
files = os.listdir(dir_name) #Открытие папки с параметрами пациентов и считывание название каждого файла в папке
len(files) # Проверяем количество считанных названий файлов в папке

5653

In [ ]:
#check = pd.read_csv("/content/patients/132551.txt")
#check['RecordID'] = check.query("Parameter == 'RecordID'").Value
#check['Age'] = check.query("Parameter == 'Age'").Value
#check['Gender'] = check.query("Parameter == 'Gender'").Value
#check['Height'] = check.query("Parameter == 'Height'").Value
#check['ICUType'] = check.query("Parameter == 'ICUType'").Value
#check['Weight'] = check.query("Parameter == 'Weight'").Value
#check
#Дорабатываю дополнение новых столбцов

,Time,Parameter,Value,RecordID,Age,Gender,Height,ICUType,Weight
0,00:00,RecordID,132551.0,132551.0,NaN,NaN,NaN,NaN,NaN
1,00:00,Age,78.0,NaN,78.0,NaN,NaN,NaN,NaN
2,00:00,DiasABP,50.0,NaN,NaN,NaN,NaN,NaN,NaN
3,00:00,Gender,0.0,NaN,NaN,0.0,NaN,NaN,NaN
4,00:00,Height,162.6,NaN,NaN,NaN,162.6,NaN,NaN
...,...,...,...,...,...,...,...,...,...
668,47:40,DiasABP,35.0,NaN,NaN,NaN,NaN,NaN,NaN
669,47:40,HR,58.0,NaN,NaN,NaN,NaN,NaN,NaN
670,47:40,MAP,61.0,NaN,NaN,NaN,NaN,NaN,NaN
671,47:40,SysABP,126.0,NaN,NaN,NaN,NaN,NaN,NaN
672,47:40,Temp,36.6,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
patients_data = pd.DataFrame() #Датафрейм со всеми пациентами
for filename in files:
    patient_data = pd.read_csv(dir_name+filename) #Считываем файл
    new_index = patient_data.loc[0] #Берем первую строку из файла (ID пациента)
    patient_data = patient_data.drop([0]) #Удаляем первую строку из Дата Фрейма
    patient_data[new_index.Parameter] = new_index.Value #Добавляем первую строку - ID пациента, как столбец
    patient_data.index = patient_data.RecordID # Ставим этот столбец как индекс
    patient_data = patient_data.drop("RecordID", axis=1) #Удаляем ненужный столбец
    patients_data = patients_data.append(patient_data) #Добавляем в общий Дата Фрейм

In [ ]:
patients_data.head() # Проверка

           Time Parameter  Value
RecordID
132774.0  00:00       Age   41.0
132774.0  00:00    Gender    1.0
132774.0  00:00    Height   -1.0
132774.0  00:00   ICUType    4.0
132774.0  00:00    Weight   89.6

In [ ]:
patients_data.reset_index().RecordID.nunique() #Проверяем количество записаных файлов

In [ ]:
all_data = pd.DataFrame() #Создаем Дата Фрейм для хранения всех данных

In [ ]:
outcomes = pd.read_csv("/content/drive/MyDrive/Outcomes_для_С1.txt") #Считываем файл с целевыми переменными
outcomes.count() #Проверяем количество

RecordID             8000
Survival             8000
In-hospital_death    8000
dtype: int64

In [ ]:
all_data = patients_data.reset_index().merge(outcomes, how="inner") # Соединяем два датафрейма по ID
all_data.head()

   RecordID   Time Parameter  Value  Survival  In-hospital_death
0  132774.0  00:00       Age   41.0        -1                  0
1  132774.0  00:00    Gender    1.0        -1                  0
2  132774.0  00:00    Height   -1.0        -1                  0
3  132774.0  00:00   ICUType    4.0        -1                  0
4  132774.0  00:00    Weight   89.6        -1                  0

In [ ]:
all_data.nunique() # Проверяем, не потеряли ли каких-либо пациентов во время соединения

RecordID              500
Time                 2881
Parameter              41
Value                1864
Survival              134
In-hospital_death       2
dtype: int64

In [ ]:
all_data.to_csv('/content/drive/MyDrive/all_data.txt',index=False) # Записываем результат в файл

In [ ]:
#Fail :(